version: '3.8'
services:
  app:
    container_name: app
    build: .
    ports:
    - 8080:8080
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/Kanban
    depends_on:
      - db
    restart: always

  db:
    container_name: db
    image: postgres:12-alpine
    ports:
    - 33333:5432
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_USER: postgres
      POSTGRES_DB: 'Kanban'
    restart: always
